flaskr/models/user.py
from flaskr import db
from sqlalchemy import Integer,String
class User(db.Model):
    __tablename__="users"
    id=db.Column(Integer,primary_key=True)
    first_name=db.Column(String(50))
    last_name=db.Column(String(50))
    email=db.Column(String(50),unique=True)
    roll_no=db.Column(String(100))

flaskr/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase
from flask_migrate import Migrate
from flask_restful import Api

class Base(DeclarativeBase):
    pass
db=SQLAlchemy(model_class=Base)
migrate=Migrate()
def create_app():
    app=Flask(__name__,instance_relative_config=True)
    app.config.from_pyfile('config.py',silent=True)
    app.config['SQLALCHEMY_DATABASE_URI']="postgresql://flask_cp7q_user:AckkG5e7ezIUxfrnH91wIWaxlnWKcqNf@dpg-cv8j7uqn91rc738jeoqg-a/flask_cp7q"
    if not app.config['SQLALCHEMY_DATABASE_URI']:
        raise ValueError("DATABASE_URL environment variable is not set!")
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False
    db.init_app(app)
    migrate.init_app(app,db)
    api=Api(app)
    #import all models here
    from flaskr.models import user
    #register all views here
    from flaskr.views import home,home_api
    app.register_blueprint(home.bp)
    #add api here
    api.add_resource(home_api.UserRegister,'/api/create')
    return app

flaskr/views/home.py
from flask import Blueprint,render_template,request,redirect,url_for
from flaskr.models.user import User
from flaskr import db
bp=Blueprint('home',__name__)

@bp.route('/',methods=['GET','POST'])
def index():
    user=User.query.all()
    if request.method=='POST':
        first_name=request.form['first_name']
        last_name=request.form['last_name']
        email=request.form['email']
        roll_no=request.form['roll_no']
        user=User(first_name=first_name,last_name=last_name,email=email,roll_no=roll_no)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('home.index'))
    return render_template('index.html',user=user)

@bp.route('/update/<int:id>',methods=['POST','GET'])
def update_user(id):
    user=User.query.get(id)
    if request.method=="POST":
        first_name=request.form['first_name']
        last_name=request.form['last_name']
        email=request.form['email']
        roll_no=request.form['roll_no']
        user.first_name=first_name
        user.last_name=last_name
        user.email=email
        user.roll_no=roll_no
        db.session.commit()
        return redirect(url_for('home.index'))
    return render_template("update.html",user=user)
@bp.route('/delete/<int:id>')
def delete_user(id):
    user=User.query.get(id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('home.index'))

flaskr/views/home_api.py
from flask_restful import Resource
from flask import request,jsonify
from flaskr.models.user import User
from flaskr import db

class UserRegister(Resource):
    def post(self):
        print("Received Headers:", request.headers)
        print("Received Content-Type:", request.content_type)
        if request.content_type != "application/json":
            return {"message": "Content-Type must be 'application/json'"}, 415
        data=request.get_json()
        print(data)
        new_user=User(first_name=data['first_name'],last_name=data['last_name'],email=data['email'],roll_no=data['roll_no'])
        db.session.add(new_user)
        db.session.commit()
        return jsonify({"message":"user created successfully"},201)

flaskr/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

flaskr/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}
<div class="container">
    <form method="post">
<div class="mb-3">
  <label for="first_name" class="form-label">First Name</label>
  <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Enter First name">
</div>
<div class="mb-3">
  <label for="last_name" class="form-label">Name</label>
  <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Enter last name">
</div>
<div class="mb-3">
  <label for="email" class="form-label">Email</label>
  <input type="email" name='email' class="form-control" id="email" placeholder="Enter email">
</div>
<div class="mb-3">
  <label for="roll_no" class="form-label">Roll No.</label>
  <input type="text" name='roll_no' class="form-control" id="roll_no" placeholder="Enter Roll">
</div>
<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
<div class="container">
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Roll No.</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
    {% for user in user %}
    <tr>
      <th scope="row">{{user.id}}</th>
      <td>{{user.first_name}}</td>
      <td>{{user.last_name}}</td>
      <td>{{user.email}}</td>
      <td>{{user.roll_no}}</td>
      <td class="mx-2"><a href="{{url_for("home.update_user",id=user.id)}}" type="button" class="btn btn-primary">Edit</a><a href="{{url_for('home.delete_user',id=user.id)}}" type="button" class="btn btn-danger">Delete</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock content %}

flaskr/templates/update.html
{% extends "base.html" %}
{% block title %}Update{% endblock title %}
{% block content %}
<div class="container">
    <form method="post">
<div class="mb-3">
  <label for="first_name" class="form-label">First Name</label>
  <input type="text" value='{{user.first_name}}' class="form-control" name="first_name" id="first_name" placeholder="Enter First name">
</div>
<div class="mb-3">
  <label for="last_name" class="form-label">Name</label>
  <input type="text" value="{{user.last_name}}" class="form-control" name="last_name" id="last_name" placeholder="Enter last name">
</div>
<div class="mb-3">
  <label for="email" class="form-label">Email</label>
  <input type="email" value="{{user.email}}" name='email' class="form-control" id="email" placeholder="Enter email">
</div>
<div class="mb-3">
  <label for="roll_no" class="form-label">Roll No.</label>
  <input type="text" value="{{user.roll_no}}" name='roll_no' class="form-control" id="roll_no" placeholder="Enter Roll">
</div>
<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock content %}